name: alpha

on: workflow_dispatch

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
      - name: Clone Dataverse repo
        uses: actions/checkout@v3
        with:
          repository: IQSS/dataverse
          path: dataverse
          ref: develop
      - name: Start containers
        run: |
          docker compose -f docker-compose-alpha.yml --env-file .env.alpha up -d
      - uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:8080/api/info/version
          timeout: 120000
          interval: 10000
      - name: Test metadatablocks
        uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:8080/api/metadatablocks
          timeout: 120000
          interval: 10000
      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose-alpha.yml --env-file .env.alpha down
