name: alpha

on: workflow_dispatch

jobs:
  test_easydataverse:
    name: Test EasyDataverse
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
      - name: Clone Dataverse repo
        uses: actions/checkout@v3
        with:
          repository: IQSS/dataverse
          path: dataverse
          ref: develop
      - name: Start containers
        run: |
          docker compose -f docker-compose-alpha.yml --env-file .env.alpha up -d
      - name: Check Dataverse Setup
        uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:8080/api/info/version
          timeout: 120000
          interval: 10000
      - name: Test metadatablocks
        uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:8080/api/metadatablocks
          timeout: 120000
          interval: 10000

      - name: Retrieve API Token
        run: |
          env
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          # python3 -m pip install .
          # python3 -m pip install pytest

          python3 -m pip install git+https://github.com/gdcc/easyDataverse.git@flexible-connect
          python3 -m pip uninstall pydataverse -y
          python3 -m pip install git+https://github.com/JR-1991/pyDataverse.git
      - name: Check connect
        run: |
          python3 ./run_ed.py 
      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose-alpha.yml --env-file .env.alpha down
