name: develop

on: workflow_dispatch

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
      - name: Clone Dataverse repo
        uses: actions/checkout@v3
        with:
          repository: IQSS/dataverse
          path: dataverse
          ref: develop
      - name: Start containers
        run: |
          docker compose -f docker-compose-develop.yml --env-file .env.develop up -d
      - uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:8080/api/info/version
          timeout: 120000
          interval: 10000
      - name: Run database sequence
        run: |
          cd dataverse
          export PGPASSWORD=secret
          # use correct database name
          sed -i 's/dvnapp/dataverse/g' doc/sphinx-guides/source/_static/util/createsequence.sql
          psql -h localhost -U dataverse dataverse -f doc/sphinx-guides/source/_static/util/createsequence.sql
      - name: Run API tests
        run: |
          cd dataverse
          INTEGRATION_TESTS=$(<tests/integration-tests.txt)
          mvn test -Dtest=$INTEGRATION_TESTS -Ddataverse.test.baseurl=http://localhost:8080
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz
      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose-develop.yml --env-file .env.develop down
