name: API Tests
on: workflow_dispatch
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Dataverse repo
        uses: actions/checkout@v3
        with:
          repository: IQSS/dataverse
          path: dataverse
          ref: develop
#       - name: Set up JDK
#         uses: actions/setup-java@v3
#         with:
#           java-version: 11
#           distribution: temurin
#           cache: maven
      - name: Start Dataverse containers
        run: |
          cd dataverse
          docker compose -f docker-compose-dev.yml up -d
      - name: Check permissions
        run: |
          docker ps
          docker exec dev_dataverse ls -l /
          docker exec dev_dataverse chown 1000:1000 /dv /secrets
          docker exec dev_dataverse ls -l /
          echo done
#       - name: Run API tests
#         run: |
#           cd dataverse
#           mvn test -Ddataverse.test.baseurl=http://localhost:8080 -Dtest=UtilIT,FitsIT
#       - name: Dump docker logs on failure
#         if: failure()
#         uses: jwalton/gh-docker-logs@v2
